### ISSUE TITLE
OverflowError: integer 4692106571 does not fit '32-bit int'

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/msl-network#1]
When creating the default self-signed certificate on a Raspberry Pi, version
```
(mslenv) pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
```
, the following exception is raised
```
(mslenv) pi@raspberrypi:~ $ msl-network start
Traceback (most recent call last):
  File "/home/pi/mslenv/bin/msl-network", line 11, in <module>
    sys.exit(main())
  File "/home/pi/mslenv/lib/python3.5/site-packages/msl/network/cli.py", line 73, in main
    sys.exit(args.func(args))
  File "/home/pi/mslenv/lib/python3.5/site-packages/msl/network/cli_start.py", line 189, in execute
    cryptography.generate_certificate(path=cert, key_path=key, key_password=key_password)
  File "/home/pi/mslenv/lib/python3.5/site-packages/msl/network/cryptography.py", line 196, in generate_certificate
    cert = cert.sign(key, hash_class, default_backend())
  File "/home/pi/mslenv/lib/python3.5/site-packages/cryptography/x509/base.py", line 577, in sign
    return backend.create_x509_certificate(self, private_key, algorithm)
  File "/home/pi/mslenv/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 796, in create_x509_certificate
    calendar.timegm(builder._not_valid_after.timetuple())
OverflowError: integer 4692106571 does not fit '32-bit int'
```
This exception results from the default ``--years-valid`` value of 100 being too large for an ARMv7 architecture (which is 32 bit).

**Comment by jborbely** [comment]
fixed in v0.3.0
